#!/bin/bash
# Instrucciones para desplegar en Vercel

echo "=== PASOS PARA DESPLEGAR EN VERCEL ==="
echo ""
echo "1. Asegúrate de que todos los cambios están en git:"
echo "   git add ."
echo "   git commit -m 'Agregar configuración de Vercel'"
echo "   git push"
echo ""
echo "2. Ve a https://vercel.com y conecta tu repositorio"
echo ""
echo "3. Vercel detectará automáticamente la configuración"
echo ""
echo "4. Una vez desplegado, prueba el endpoint:"
echo "   GET: https://tu-proyecto.vercel.app/api?board=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]"
echo ""
echo "5. Si recibís 404, limpia el caché en Vercel y redeploy"
echo ""
echo "=== ARCHIVOS CREADOS/MODIFICADOS ==="
echo "✓ vercel.json - Configuración de Vercel"
echo "✓ api/index.js - Función serverless"
echo "✓ package.json - Actualizado con motor de Node"
echo "✓ .nvmrc - Versión de Node 20"
echo "✓ README_VERCEL.md - Documentación completa"
